version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - /srv/http-proxy/development:/app/development
      - /srv/http-proxy/routes:/app/routes
    restart: unless-stopped